### ISSUE TITLE
Duplicated window buttons on Firefox and Chrome

### ISSUE THREAD

**Issue by marciosg4** [hardpixel/unite-shell#239]
Some apps, like firefox and google chrome displays duplicated window buttons when the window is maximized.

OS: Ubuntu 20.04
Unite_shell: v50

![2021-04-20_21-15](https://user-images.githubusercontent.com/8688092/115479145-2a759680-a21e-11eb-8b49-1ad6d4d2fdd4.png)
![2021-04-20_21-16](https://user-images.githubusercontent.com/8688092/115479147-2b0e2d00-a21e-11eb-8748-2964fbc29fe4.png)

**Comment by jonian** [comment]
Hi @marciosg4, for Google Chrome you can enable "Use system titlebar and borders". For Firefox in customize screen you can disable "Title bar" or you can add in `~/.mozilla/firefox/yourprofile/chrome/userChrome.css`:

```css
#main-window[sizemode="maximized"] .titlebar-buttonbox-container  {
  display: none !important;
}
```

This issue has come up several times, so maybe it should be added in the readme.
