### ISSUE TITLE
[Compatibility] No spacing in menubar widgets from Vitals extension

### ISSUE THREAD

**Issue by corecoding** [hardpixel/unite-shell#68]
I am the author of Vitals, a gnome extension to show system resources. Users have reported (https://github.com/corecoding/Vitals/issues/41) that the spacing between sensors in the menubar are non existent when using the Unite plugin. My spacing is applied using css. Any ideas on how to make our plugins live harmoniously?

**Comment by jonian** [comment]
Hi @corecoding, thank you for reporting. I will make the required compatibility fixes. Please provide a link to the line/file that creates the panel buttons.

Unite uses nested paths to override the panel styles. Maybe you should use them too, so themes and extensions do not override your styles. For example:

```css
/** Initial style **/
.vitals-icon { icon-size: 16px; }

/** With nested path **/
#panel .vitals-panel-box .vitals-icon { icon-size: 16px; }
```
All unite panel styles are [here](https://github.com/hardpixel/unite-shell/blob/master/unite%40hardpixel.eu/stylesheet.css). The rules that modify panel widgets that are not created by unite are:

```css
#panel .panel-button {
  -natural-hpadding: 8px;
  -minimum-hpadding: 6px;
}

#panel .panel-button .system-status-icon {
  margin: 0;
  padding: 0;
}

#panel .panel-button .panel-status-menu-box {
  margin: 0;
  padding: 0;
  spacing: 0;
}

#panel .panel-button .panel-status-indicators-box {
  spacing: 10px;
}

#panel .panel-button .panel-status-indicators-box .popup-menu-arrow {
  width: 12px;
  height: 12px;
}

#panel .popup-menu-arrow,
#panel .app-menu-icon {
  width: 0;
  height: 0;
  margin: 0;
  padding: 0;
}

#panel #appMenu {
  margin-left: 8px;
  margin-right: 3px;
}

#panel #appMenu .popup-menu-arrow {
  margin-left: 5px;
}

#panel #appMenu .app-menu-icon > StIcon {
  icon-shadow: none;
}
```
